---
abstract: 'Producer and Consumer classes for Amazon Simple Queue Service (SQS)'
author:
  - 'Nic Wolff <nic@angel.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amazon-SQS-ProducerConsumer
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Digest::HMAC_SHA1: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Test::More: 0
  URI::Escape: 0
  XML::Simple: 0
version: 0.03
